# EE build of the installer ELF. Invoked by the top-level Makefile.
# Pattern follows ps2-usbhdl's Makefile (b681bc6): IRX modules and
# assets are embedded as bin2c blobs so nothing is loaded from media.

BUILD ?= build/ee
EE_BIN ?= dist/desr-udpfs-installer.elf
NEUTRINO_IRX_DIR ?= build/irx
OPL_LAUNCHER_KELF ?=

SRC_DIR := src

# Standard PS2SDK modules.
SDK_IRX := iomanX fileXio poweroff ps2dev9 ps2atad ps2fs sio2man padman
# HDLGameInstaller (ec37c81) modules; identical to ps2-usbhdl's vendored
# copies. ps2hdd-hdl.irx is taken from $(NEUTRINO_IRX_DIR) after
# tools/patch-ps2hdd-hdl.py (removal of "__." partitions).
HDL_IRX := ps2hdd_hdl hdlfs
NEU_IRX := smap ministack udpfs_ioman

SRCS := main.c app_state.c iop_boot.c network.c source.c source_udpfs.c \
        iso9660.c hdl_plan.c hdl_header.c hdl_install.c hdd_partitions.c \
        pfs_channel.c apa_osd_header.c opl_dependency.c opl_launcher_payload.c \
        xmb_installer_app.c xmb_game_channel.c xmb_text.c transaction.c \
        settings.c ui.c partname.c errors.c util.c game_pair.c browser.c flows.c

BLOBS := $(addsuffix _irx,$(SDK_IRX) $(HDL_IRX) $(NEU_IRX)) default_jkt_png installer_jkt_png

EE_OBJS := $(addprefix $(BUILD)/,$(SRCS:.c=.o)) $(addprefix $(BUILD)/blob_,$(addsuffix .o,$(BLOBS)))

ifneq ($(strip $(OPL_LAUNCHER_KELF)),)
EE_OBJS += $(BUILD)/blob_opl_launcher_kelf.o
EE_CFLAGS += -DHAVE_EMBEDDED_OPL_LAUNCHER
endif

EE_LIBS = -ldebug -lhdd -lpoweroff -lfileXio -lpatches -lpad
EE_CFLAGS += -std=gnu11 -Wextra -Werror -Wno-unused-parameter -D_EE
EE_INCS += -I$(SRC_DIR)

all: $(EE_BIN)

$(BUILD)/%.o: $(SRC_DIR)/%.c $(wildcard $(SRC_DIR)/*.h)
	@mkdir -p $(@D)
	$(EE_CC) $(EE_CFLAGS) $(EE_INCS) -c $< -o $@

# bin2c blobs
$(BUILD)/blob_%_irx.c: $(PS2SDK)/iop/irx/%.irx
	@mkdir -p $(@D)
	bin2c $< $@ $*_irx
$(BUILD)/blob_ps2hdd_hdl_irx.c: $(NEUTRINO_IRX_DIR)/ps2hdd-hdl.irx
	@mkdir -p $(@D)
	bin2c $< $@ ps2hdd_hdl_irx
$(BUILD)/blob_hdlfs_irx.c: reference/HDLGameInstaller/irx/hdlfs.irx
	@mkdir -p $(@D)
	bin2c $< $@ hdlfs_irx
$(BUILD)/blob_smap_irx.c: $(NEUTRINO_IRX_DIR)/smap.irx
	@mkdir -p $(@D)
	bin2c $< $@ smap_irx
$(BUILD)/blob_ministack_irx.c: $(NEUTRINO_IRX_DIR)/ministack.irx
	@mkdir -p $(@D)
	bin2c $< $@ ministack_irx
$(BUILD)/blob_udpfs_ioman_irx.c: $(NEUTRINO_IRX_DIR)/udpfs_ioman.irx
	@mkdir -p $(@D)
	bin2c $< $@ udpfs_ioman_irx
$(BUILD)/blob_default_jkt_png.c: assets/game/default_jkt_001.png
	@mkdir -p $(@D)
	bin2c $< $@ default_jkt_png
$(BUILD)/blob_installer_jkt_png.c: assets/installer/jkt_001.png
	@mkdir -p $(@D)
	bin2c $< $@ installer_jkt_png
$(BUILD)/blob_opl_launcher_kelf.c: $(OPL_LAUNCHER_KELF)
	@mkdir -p $(@D)
	bin2c $< $@ opl_launcher_kelf

$(BUILD)/blob_%.o: $(BUILD)/blob_%.c
	$(EE_CC) $(EE_CFLAGS) -c $< -o $@

.SECONDARY:

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
