#!/usr/bin/env bash
# Generate build_info.c for one installer build variant.
#
#   gen-build-info.sh <out.c> <variant> <symbol>=<file> ...
#
# Each <symbol> is the bin2c name of an embedded blob; its SHA-256 and
# size are recorded so the console's diagnostics page can recompute and
# compare them. Output is deterministic (commit id and commit date, no
# wall clock) and only rewritten when it changes.
set -euo pipefail
OUT=$1
VARIANT=$2
shift 2
ROOT=$(cd "$(dirname "$0")/.." && pwd)
ID=$(git -C "$ROOT" describe --always --dirty --abbrev=12 2>/dev/null || echo unknown)
DATE=$(git -C "$ROOT" log -1 --format=%cI 2>/dev/null || echo unknown)
{
  echo '/* Generated by tools/gen-build-info.sh. Do not edit. */'
  echo '#include <string.h>'
  echo '#include "build_info.h"'
  echo "const char build_id[] = \"$ID\";"
  echo "const char build_variant[] = \"$VARIANT\";"
  echo "const char build_date[] = \"$DATE\";"
  echo 'const build_blob_t build_blobs[] = {'
  for kv in "$@"; do
    sym=${kv%%=*}
    file=${kv#*=}
    sha=$(sha256sum "$file" | cut -d' ' -f1)
    size=$(stat -c %s "$file")
    echo "  {\"$sym\", \"$sha\", $size},"
  done
  echo '};'
  echo "const int build_nblobs = $#;"
  echo 'const build_blob_t *build_blob(const char *name) {'
  echo '  for (int i = 0; i < build_nblobs; i++)'
  echo '    if (strcmp(build_blobs[i].name, name) == 0)'
  echo '      return &build_blobs[i];'
  echo '  return NULL;'
  echo '}'
} > "$OUT.tmp"
if cmp -s "$OUT.tmp" "$OUT"; then rm -f "$OUT.tmp"; else mv "$OUT.tmp" "$OUT"; fi
